### PR TITLE
multiple auth0 configs

### PR DESCRIPTION
**Pull request by kratsg**
I'm also setting `NODE_ENV` on our staging server to `staging`. Right now, the variables look like this for staging:

screenshot 2018-01-29 08 57 39

### CODE REVIEW

**Comment by meltedspork** [comment]
Hmm. looks like tests failed. Something to do with AUTH0.<properties> not being passable.

**Comment by kratsg** [comment]
is `NODE_ENV` undefined for the tests?

**Comment by meltedspork** [comment]
you can add `process.env.NODE_ENV = 'test';` somewhere at this file https://github.com/deafchi/signsfive-web/blob/master/tests/setupTests.js#L12

**Comment by kratsg** [comment]
Why do the tests need the AUTH0 config variables? This is the part I'm a bit confused by. We can't really test this portion since it's technically an integration test.

**Comment by meltedspork** [comment]
Another i would suggestion using `sinon` with `stub` to stub fake callback and focus on non-integrated way.

**Comment by kratsg** [comment]
> Another i would suggestion using sinon with stub to stub fake callback and focus on non-integrated way.

Main issue is that it's trying to load the AUTH0 configuration which (obviously) doesn't exist for the `test` environment.

**Comment by meltedspork** [comment]
> Main issue is that it's trying to load the AUTH0 configuration which (obviously) doesn't exist for the test environment.

Yeah, and after looking at the `AuthService.js` - it appears that we might have coupled AuthService and Auth0 too tightly as proven by tests. We can decouple it more and it will also make it more testability . What I would do is take line 12 to 21 out of `AuthService.js` and then create Auth0 own exportable file and we import it into `AuthService.js` instead. We might need to stub the imported AUTH0 a bit i think.

**Comment by kratsg** [comment]
> Yeah, and after looking at the AuthService.js - it appears that we might have coupled AuthService and Auth0 too tightly as proven by tests. We can decouple it more and it will also make it more testability . What I would do is take line 12 to 21 out of AuthService.js and then create Auth0 own exportable file and we import it into AuthService.js instead. We might need to sinon.stub the imported AUTH0 a bit in existing tests, i think.

Sure. I'm not gonna have time to fix that part so quickly. I'm not familiar enough with `sinon`.

**Comment by meltedspork** [comment]
I’ll approve this pr and create ticket to fix test. I’m familiar with it enough.

**Pull request merged**
